[package]
name = "alpha"
version = "0.1.0"
authors = ["oooutlk <oooutlk@outlook.com>"]
edition = "2021"
publish = false

[dependencies]
echo = { path = "../echo" }

[build-dependencies]
inwelling = { path = "../.." }

[package.metadata.inwelling.echo]
alpha = "the first letter"
