[package]
name = "alpha"
version = "0.1.0"
authors = ["oooutlk <oooutlk@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
echo = { path = "../echo" }

[package.metadata.inwelling.echo]
alpha = true
