[package]
name = "gamma"
version = "0.1.0"
authors = ["oooutlk <oooutlk@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
echo = { path = "../echo" }
alpha = { path = "../alpha" }
beta = { path = "../beta", optional = true }

[package.metadata.inwelling.echo]
gamma = true
